name: crickarena
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  battery_plus: ^4.0.2
  geolocator: ^10.0.1
  image_picker: ^1.0.4
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.2
  cloud_firestore: ^5.6.8
  provider: ^6.1.5
  google_maps_flutter: ^2.12.2
  mailer: ^6.4.1
  lottie: ^3.3.1
  http: ^1.4.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  local_auth: ^2.3.0
  webview_flutter: ^4.13.0

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.1.5
  flutter_launcher_icons: ^0.14.3
    
 
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  image_path: "assets/images/CRrgan 1.png"
  android: true
  ios: true
  web: 
    generate: true
    image_path: "assets/images/CRrgan 1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/products.json
    - assets/animations/


 
